import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { ApiService } from '../../../core/api/api.service';

/** Platform i18n admin API (requires platform JWT). */
const BASE = 'v1/platform/i18n';

export interface I18nLabelDto {
  label_id: number;
  label_key: string;
  module_id: number | null;
}

export interface I18nLabelWithTranslationsDto extends I18nLabelDto {
  pending_translation?: boolean;
  translations: Record<string, string>;
}

export interface LabelsWithTranslationsResponseDto {
  languages: { code: string; name: string }[];
  labels: I18nLabelWithTranslationsDto[];
}

export interface LabelTranslationsDto {
  label: string;
  translations: { lang: string; text: string; autoGenerated?: boolean }[];
}

export interface I18nLanguageDto {
  id: string;
  code: string;
  name: string;
}

export interface MissingByLangDto {
  lang: string;
  missing: { label_id: number; label_key: string }[];
}

/** Respuesta de POST /sync (diccionarios → BD). */
export interface I18nSyncResultDto {
  newLabels: number;
  newTranslations: number;
  autoGeneratedCount?: number;
  /** Origen de claves: TS del admin o fallback JS de la API. */
  dictionarySource: 'platform-admin-ts' | 'api-dictionaries-js';
  /** Total de claves planas en el diccionario (unión es+en). */
  keysScanned: number;
}

@Injectable({ providedIn: 'root' })
export class TranslationsApiService {
  private readonly api = inject(ApiService);

  getLabels(): Observable<I18nLabelDto[]> {
    return this.api.get<I18nLabelDto[]>(`${BASE}/labels`);
  }

  getLabelsWithTranslations(): Observable<LabelsWithTranslationsResponseDto> {
    return this.api.get<LabelsWithTranslationsResponseDto>(`${BASE}/labels/with-translations`);
  }

  getLanguages(): Observable<I18nLanguageDto[]> {
    return this.api.get<I18nLanguageDto[]>(`${BASE}/languages`);
  }

  getMissingByLang(lang: string): Observable<MissingByLangDto> {
    return this.api.get<MissingByLangDto>(`${BASE}/missing/${encodeURIComponent(lang)}`);
  }

  getLabelTranslations(labelKey: string): Observable<LabelTranslationsDto> {
    const encoded = encodeURIComponent(labelKey);
    return this.api.get<LabelTranslationsDto>(`${BASE}/labels/${encoded}`);
  }

  updateTranslation(labelKey: string, lang: string, text: string): Observable<{ labelKey: string; lang: string; text: string }> {
    return this.api.put<{ labelKey: string; lang: string; text: string }>(`${BASE}/translation`, {
      labelKey,
      lang,
      text,
    });
  }

  createTranslation(labelKey: string, lang: string, text: string): Observable<{ labelKey: string; lang: string; text: string }> {
    return this.api.post<{ labelKey: string; lang: string; text: string }>(`${BASE}/translation`, {
      labelKey,
      lang,
      text,
    });
  }

  /** Inserta en BD claves y textos que vienen de los diccionarios del servidor (sin sobrescribir lo ya guardado). */
  syncFromDictionaries(): Observable<I18nSyncResultDto> {
    return this.api.post<I18nSyncResultDto>(`${BASE}/sync`, {});
  }
}
