export interface ThemePalette {
  id: string;
  name: string;
  primaryColor: string;
  /** Acento de marca (badges, links, highlights). */
  accentColor: string;
  /** @deprecated Metadatos legacy; la UI ya no los edita directamente. */
  sidebarBgColor?: string;
  headerBgColor?: string;
  pageBackgroundColor?: string;
  buttonPrimaryColor?: string;
  buttonSecondaryColor?: string;
  textColor?: string;
}

export const THEME_PALETTES: ThemePalette[] = [
  {
    id: 'ocean',
    name: 'Ocean',
    primaryColor: '#1F6FEB',
    accentColor: '#4DD2F0',
    sidebarBgColor: '#1F6FEB',
    headerBgColor: '#F4ECE4',
    buttonPrimaryColor: '#1F6FEB',
    buttonSecondaryColor: '#F4ECE4',
    textColor: '#012630',
  },
  {
    id: 'royal',
    name: 'Royal',
    primaryColor: '#1976D2',
    accentColor: '#DC004E',
    sidebarBgColor: '#1976D2',
    headerBgColor: '#EEF4FF',
    buttonPrimaryColor: '#1976D2',
    buttonSecondaryColor: '#DC004E',
    textColor: '#0B1F3A',
  },
  {
    id: 'forest',
    name: 'Forest',
    primaryColor: '#2E7D32',
    accentColor: '#C6A86A',
    sidebarBgColor: '#2E7D32',
    headerBgColor: '#F3F7EE',
    buttonPrimaryColor: '#2E7D32',
    buttonSecondaryColor: '#C6A86A',
    textColor: '#1B2A1E',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    primaryColor: '#E65100',
    accentColor: '#8E24AA',
    sidebarBgColor: '#E65100',
    headerBgColor: '#FFF3E0',
    buttonPrimaryColor: '#E65100',
    buttonSecondaryColor: '#8E24AA',
    textColor: '#2A1A12',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    primaryColor: '#1E3A8A',
    accentColor: '#14B8A6',
    sidebarBgColor: '#1E3A8A',
    headerBgColor: '#EEF2FF',
    buttonPrimaryColor: '#1E3A8A',
    buttonSecondaryColor: '#14B8A6',
    textColor: '#0B1739',
  },
  {
    id: 'grape',
    name: 'Grape',
    primaryColor: '#7C3AED',
    accentColor: '#F59E0B',
    sidebarBgColor: '#6D28D9',
    headerBgColor: '#F5F3FF',
    buttonPrimaryColor: '#7C3AED',
    buttonSecondaryColor: '#F59E0B',
    textColor: '#22153F',
  },
  {
    id: 'ruby',
    name: 'Ruby',
    primaryColor: '#B91C1C',
    accentColor: '#F59E0B',
    sidebarBgColor: '#991B1B',
    headerBgColor: '#FEF2F2',
    buttonPrimaryColor: '#B91C1C',
    buttonSecondaryColor: '#F59E0B',
    textColor: '#2E1111',
  },
  {
    id: 'lime',
    name: 'Lime',
    primaryColor: '#3F6212',
    accentColor: '#0EA5E9',
    sidebarBgColor: '#365314',
    headerBgColor: '#F7FEE7',
    buttonPrimaryColor: '#3F6212',
    buttonSecondaryColor: '#0EA5E9',
    textColor: '#172112',
  },
  {
    id: 'sand',
    name: 'Sand',
    primaryColor: '#9A6B2F',
    accentColor: '#2563EB',
    sidebarBgColor: '#8A5F28',
    headerBgColor: '#FAF6EF',
    buttonPrimaryColor: '#9A6B2F',
    buttonSecondaryColor: '#2563EB',
    textColor: '#2A2116',
  },
  {
    id: 'slate',
    name: 'Slate',
    primaryColor: '#334155',
    accentColor: '#0EA5E9',
    sidebarBgColor: '#1E293B',
    headerBgColor: '#F1F5F9',
    buttonPrimaryColor: '#334155',
    buttonSecondaryColor: '#0EA5E9',
    textColor: '#0F172A',
  },
  {
    id: 'indigo-pop',
    name: 'Indigo Pop',
    primaryColor: '#4F46E5',
    accentColor: '#EC4899',
    sidebarBgColor: '#4338CA',
    headerBgColor: '#EEF2FF',
    buttonPrimaryColor: '#4F46E5',
    buttonSecondaryColor: '#EC4899',
    textColor: '#1E1B4B',
  },
  {
    id: 'teal-night',
    name: 'Teal Night',
    primaryColor: '#0F766E',
    accentColor: '#F97316',
    sidebarBgColor: '#115E59',
    headerBgColor: '#ECFEFF',
    buttonPrimaryColor: '#0F766E',
    buttonSecondaryColor: '#F97316',
    textColor: '#112A2A',
  },
  {
    id: 'rose',
    name: 'Rose',
    primaryColor: '#E11D48',
    accentColor: '#2563EB',
    sidebarBgColor: '#BE123C',
    headerBgColor: '#FFF1F2',
    buttonPrimaryColor: '#E11D48',
    buttonSecondaryColor: '#2563EB',
    textColor: '#3A1020',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    primaryColor: '#059669',
    accentColor: '#7C3AED',
    sidebarBgColor: '#047857',
    headerBgColor: '#ECFDF5',
    buttonPrimaryColor: '#059669',
    buttonSecondaryColor: '#7C3AED',
    textColor: '#0F2E24',
  },
  {
    id: 'amber',
    name: 'Amber',
    primaryColor: '#D97706',
    accentColor: '#0EA5E9',
    sidebarBgColor: '#B45309',
    headerBgColor: '#FFFBEB',
    buttonPrimaryColor: '#D97706',
    buttonSecondaryColor: '#0EA5E9',
    textColor: '#2E1E10',
  },
  {
    id: 'graphite',
    name: 'Graphite',
    primaryColor: '#111827',
    accentColor: '#10B981',
    sidebarBgColor: '#0B1220',
    headerBgColor: '#F3F4F6',
    buttonPrimaryColor: '#111827',
    buttonSecondaryColor: '#10B981',
    textColor: '#111827',
  },
];
