import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { forkJoin } from 'rxjs';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { PlatformTranslatePipe } from '../../../core/i18n/translate.pipe';
import { DbTranslationsLoaderService } from '../../../core/i18n/db-translations.loader';
import { TranslationsApiService } from '../services/translations-api.service';

export interface TranslationEditDialogData {
  labelKey: string;
}

/** Resultado al cerrar tras guardar (para actualizar la fila sin recargar la lista). */
export interface TranslationEditDialogSaveResult {
  saved: true;
  labelKey: string;
  /** Solo idiomas que se enviaron a la API (claves fusionadas en la tabla). */
  translations: Record<string, string>;
}

@Component({
  selector: 'app-translation-edit-dialog',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatDialogModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    PlatformTranslatePipe,
  ],
  templateUrl: './translation-edit-dialog.component.html',
  styleUrls: ['./translation-edit-dialog.component.scss'],
})
export class TranslationEditDialogComponent implements OnInit {
  private readonly data = inject<TranslationEditDialogData>(MAT_DIALOG_DATA);
  private readonly ref = inject(MatDialogRef<TranslationEditDialogComponent>);
  private readonly api = inject(TranslationsApiService);
  private readonly dbTranslations = inject(DbTranslationsLoaderService);
  private readonly fb = inject(FormBuilder);

  readonly labelKey = this.data.labelKey;
  readonly loading = signal(true);
  readonly saving = signal(false);
  readonly error = signal<string | null>(null);
  private existingLangs = new Set<string>();

  readonly form = this.fb.nonNullable.group({
    es: [''],
    en: [''],
  });

  /** Which languages have autoGenerated translation (show hint in UI). */
  readonly autoGeneratedLangs = signal<Set<string>>(new Set());

  readonly languages = [
    { code: 'es', labelKey: 'translations.langEs' },
    { code: 'en', labelKey: 'translations.langEn' },
  ] as const;

  ngOnInit(): void {
    this.api.getLabelTranslations(this.labelKey).subscribe({
      next: (res) => {
        const byLang: Record<string, string> = {};
        const autoGen = new Set<string>();
        for (const t of res.translations) {
          byLang[t.lang] = t.text;
          this.existingLangs.add(t.lang);
          if (t.autoGenerated) autoGen.add(t.lang);
        }
        this.autoGeneratedLangs.set(autoGen);
        this.form.patchValue({
          es: byLang['es'] ?? '',
          en: byLang['en'] ?? '',
        });
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set(err?.message ?? 'Error al cargar traducciones');
        this.loading.set(false);
        this.form.patchValue({ es: '', en: '' });
      },
    });
  }

  save(): void {
    this.saving.set(true);
    this.error.set(null);
    const v = this.form.getRawValue();
    const requests: ReturnType<TranslationsApiService['updateTranslation']>[] = [];
    const savedTranslations: Record<string, string> = {};
    for (const lang of ['es', 'en'] as const) {
      const text = v[lang].trim();
      if (!text) continue;
      savedTranslations[lang] = text;
      const req = this.existingLangs.has(lang)
        ? this.api.updateTranslation(this.labelKey, lang, text)
        : this.api.createTranslation(this.labelKey, lang, text);
      requests.push(req);
    }
    if (requests.length === 0) {
      this.saving.set(false);
      return;
    }
    forkJoin(requests).subscribe({
      next: () => {
        this.saving.set(false);
        // Actualizar textos en memoria para ngx-translate; no bloquea el cierre del diálogo
        this.dbTranslations.loadFromDb().subscribe();
        const result: TranslationEditDialogSaveResult = {
          saved: true,
          labelKey: this.labelKey,
          translations: savedTranslations,
        };
        this.ref.close(result);
      },
      error: (err) => {
        this.error.set(err?.message ?? 'Error al guardar');
        this.saving.set(false);
      },
    });
  }

  cancel(): void {
    this.ref.close(false);
  }
}
